language: c
sudo: false
dist: trusty
addons:
  apt:
    packages: &1
    - lcov
    - valgrind
    - doxygen
matrix:
  include:
  - os: linux
    addons:
      apt:
        packages:
        - *1
        - g++-4.8
    env:
    - MATRIX_EVAL="CC=gcc-4.8 && CXX=g++-4.8"
  - os: linux
    addons:
      apt:
        sources:
        - ubuntu-toolchain-r-test
        packages:
        - *1
        - g++-4.9
    env:
    - MATRIX_EVAL="CC=gcc-4.9 && CXX=g++-4.9"
  - os: linux
    addons:
      apt:
        sources:
        - ubuntu-toolchain-r-test
        packages:
        - *1
        - g++-5
    env:
    - MATRIX_EVAL="CC=gcc-5 && CXX=g++-5"
  - os: linux
    addons:
      apt:
        sources:
        - ubuntu-toolchain-r-test
        packages:
        - *1
        - g++-6
    env:
    - MATRIX_EVAL="CC=gcc-6 && CXX=g++-6"
  - os: linux
    addons:
      apt:
        sources:
        - ubuntu-toolchain-r-test
        packages:
        - *1
        - g++-7
    env:
    - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"
  - os: linux
    addons:
      apt:
        sources:
        - ubuntu-toolchain-r-test
        - llvm-toolchain-precise-3.6
        packages:
        - *1
        - clang-3.6
    env:
    - MATRIX_EVAL="CC=clang-3.6 && CXX=clang++-3.6"
  - os: linux
    addons:
      apt:
        sources:
        - ubuntu-toolchain-r-test
        - llvm-toolchain-precise-3.7
        packages:
        - *1
        - clang-3.7
    env:
    - MATRIX_EVAL="CC=clang-3.7 && CXX=clang++-3.7"
  - os: linux
    addons:
      apt:
        sources:
        - ubuntu-toolchain-r-test
        - llvm-toolchain-precise-3.8
        packages:
        - *1
        - clang-3.8
    env:
    - MATRIX_EVAL="CC=clang-3.8 && CXX=clang++-3.8"
  - os: linux
    addons:
      apt:
        sources:
        - llvm-toolchain-trusty-4.0
        packages:
        - *1
        - clang-4.0
    env:
    - MATRIX_EVAL="CC=clang-4.0 && CXX=clang++-4.0"
  - os: linux
    addons:
      apt:
        sources:
        - llvm-toolchain-trusty-5.0
        packages:
        - *1
        - clang-5.0
    env:
    - MATRIX_EVAL="CC=clang-5.0 && CXX=clang++-5.0"
branches:
  only:
  - master
cache:
  directories:
  - $HOME/install
before_install:
- eval "${MATRIX_EVAL}"
- ./scripts/install-deps.sh "$HOME/install"
script:
- ./scripts/build.sh "$HOME/install"
after_success:
- ./scripts/upload-coverage.sh
- ./scripts/generate-doc.sh && touch build/doc/Debug/html/.nojekyll
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  local-dir: build/doc/Debug/html
env:
  global:
  - LANG="en_US.UTF-8"
  - PATH="$HOME/install/bin:$PATH"
  - COVERAGE="ON"
  - secure: ddrPCYo9bl6vPVqIboq59TVxFtRhZuElfg8gzb1OASe9l8X68+pshbKakJ6/WVWzl8Y6jV2f5oSrqJq8PRoClQ6AnHDws2kbz2pcwlOxmcJn5tokHYd/CwtAG9Gwu3JHv1sVwvYlR7PWpKznxVTw/vixBOlXDRtDBxHv9Y7Cr8BUyFBz+1q7cVAk7H8V+t3DhWXT/FoqLRhTrlML+WT+mupZ3WdNpmDuMnt+4GuzgTvTkjq8PN2ue/CEpodc6xLUyTIRrOCN19UsR3EZ4/FbwFDgfOQfGdrLqt0YFh8yOKislixKyOCufchjd7ar6NBH4H6SjPJ9Fi972one7QU8sUb13/iq8MmNLfQSTATvpF0p+eGTFQg3bn969HqWOOS/zLEDtneMM5kFF7JvXgjVuhZbTlQ1MJj53x7v51h+btEiv1TwIiPd0rOpmhXrBiR6usNfncxYt4E771yBGoxxoYQx5HIX1WRJoreEa+S6zF4WwUWysKK7/apCPLjztsKXyx2gyN17xzJEwJOKC+6mGmrOQA9mWRba9GxE/8/BxF35/04WFpX7lkEh7p9jgSbgHXe2tx6mfxysnQahW0lPTTpa5xd9tp7Haj2H4wIeVv9KGSqq2bTSrmTYBJ8reb/23vTOdUdj4XEvhoiaSei86HL/COAImrGAuyoy9KnqDwo=
  - secure: TPQ6zW8SA4Cw5cDfUZ0VfiGcxDSUvo2p2gKSHvyvpffZCAYss0D3eOyqD/f1q0q1iLQx6OAkLfOiTV6aV5BNo+5NwWptoqOfFt+nyj1BK/05mNlsuSBWpHKuPwHuJ8UxZ+ukWi3JIRzzP5tpNvET1wOcdH0jVr7B1ztQt8H/HiHfYIkXGY0MYg2I8V8SouBlssmqSp25iWMWKn7lG+UPHYVtJ+l7ca4WysStl0yFDdbor1xCCjC/hBGj++F2Ri0Wn8dQIYnnFkqpQZ5zD8JXYweUy7cQJ5+vZZrEZwAbh33znMaaEDVcJPc9OsFr91cvw78GtqnAOBASgyWFJf3F8FEAvSRRNBTwN150Adcjwujo9D3sncc5Q9yCiz64t80jMVOouQ1IJ2uFyeIgigXOziI+z7c+rpMEmLXNmXTof4T7VOhQ/ytjJalb4PRADydLVNFUiATQzXOirLyf5AFukQpF36ak9Z1yShmBUbGQXliO9uASaDDm3ABsksgF9zWQY9d5KRJByCuO4XoYaBkf1eWIj0zcsMKJF6KwlGQw1HMku1kK9tZkwJwd2PqZ80iYCFJKrjFl0Ulujln7omUnLN2qG0Sp1VEg51xLGaI98KiZTAztM05Zx0pjdvQ2b0RkvxgEhqxLdncpnrBK0Z1HWOM3whrhN3puY0YsQSgcoyI=
